# ruff: noqa: E501 - generated DDL strings
"""Add reference data and assessment tables (GRP-ARC-001 Section 12, Increment 1).

Revision ID: 20260916_0004
Revises: 20260916_0003
Create Date: 2026-09-16 16:15:11.925546
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "20260916_0004"
down_revision: str | None = "20260916_0003"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "boundary",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("admin_code", sa.String(length=64), nullable=False),
        sa.Column("admin_level", sa.String(length=32), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column(
            "geom",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("source", sa.String(length=200), nullable=False),
        sa.Column("edition", sa.String(length=100), nullable=False),
        sa.Column("geometry_sha256", sa.String(length=64), nullable=False),
        sa.Column("is_supported", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_boundary_admin_code"), "boundary", ["admin_code"], unique=False)
    op.create_table(
        "method",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("key", sa.String(length=100), nullable=False),
        sa.Column("version", sa.String(length=32), nullable=False),
        sa.Column(
            "reason_codes",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("approved_by", sa.String(length=200), nullable=True),
        sa.Column("approved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("status IN ('draft', 'approved', 'retired')", name="ck_method_status"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("key", "version", name="uq_method_key_version"),
    )
    op.create_table(
        "assessment",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("hub_id", sa.Uuid(), nullable=False),
        sa.Column("submitted_by", sa.Uuid(), nullable=False),
        sa.Column("idempotency_key", sa.String(length=128), nullable=False),
        sa.Column("request_sha256", sa.String(length=64), nullable=False),
        sa.Column("boundary_id", sa.Uuid(), nullable=False),
        sa.Column("method_id", sa.Uuid(), nullable=False),
        sa.Column(
            "inputs",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("state", sa.String(length=16), nullable=False),
        sa.Column("lease_until", sa.DateTime(timezone=True), nullable=True),
        sa.Column("attempt", sa.Integer(), nullable=False),
        sa.Column(
            "summary",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=True,
        ),
        sa.Column("error_code", sa.String(length=64), nullable=True),
        sa.Column("sharing_state", sa.String(length=24), nullable=False),
        sa.Column("shared_by", sa.Uuid(), nullable=True),
        sa.Column("shared_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("sig_pack_id", sa.String(length=200), nullable=True),
        sa.Column("sig_report_id", sa.String(length=200), nullable=True),
        sa.Column("sig_receipt_id", sa.String(length=200), nullable=True),
        sa.Column("draft_sha256", sa.String(length=64), nullable=True),
        sa.Column("trace_id", sa.String(length=64), nullable=True),
        sa.Column("support_ref", sa.String(length=32), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "sharing_state IN ('private', 'shared', 'sig_unavailable', 'receipt_issued', 'unshared')",
            name="ck_assessment_sharing_state",
        ),
        sa.CheckConstraint(
            "state IN ('queued', 'running', 'succeeded', 'failed', 'cancelled')",
            name="ck_assessment_state",
        ),
        sa.ForeignKeyConstraint(["boundary_id"], ["boundary.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["hub_id"], ["hub.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["method_id"], ["method.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["shared_by"], ["app_user.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["submitted_by"], ["app_user.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "submitted_by", "hub_id", "idempotency_key", name="uq_assessment_idempotency"
        ),
    )
    op.create_index(op.f("ix_assessment_hub_id"), "assessment", ["hub_id"], unique=False)
    op.create_index(op.f("ix_assessment_state"), "assessment", ["state"], unique=False)
    op.create_table(
        "dataset",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("hub_id", sa.Uuid(), nullable=True),
        sa.Column("type", sa.String(length=32), nullable=False),
        sa.Column("owner_kind", sa.String(length=16), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("provider", sa.String(length=200), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("owner_kind IN ('platform', 'hub_local')", name="ck_dataset_owner"),
        sa.CheckConstraint(
            "type IN ('hazard', 'evacuation_centers', 'vulnerability')", name="ck_dataset_type"
        ),
        sa.ForeignKeyConstraint(["hub_id"], ["hub.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "dataset_version",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("dataset_id", sa.Uuid(), nullable=False),
        sa.Column("storage_key", sa.String(length=500), nullable=True),
        sa.Column("sha256", sa.String(length=64), nullable=False),
        sa.Column("return_period_years", sa.Integer(), nullable=True),
        sa.Column(
            "metadata",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("is_current", sa.Boolean(), nullable=False),
        sa.Column("accepted_by", sa.Uuid(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "return_period_years IS NULL OR return_period_years IN (10, 20, 50, 75, 100, 200, 500)",
            name="ck_dataset_version_return_period",
        ),
        sa.ForeignKeyConstraint(["accepted_by"], ["app_user.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["dataset_id"], ["dataset.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_dataset_version_dataset_id"), "dataset_version", ["dataset_id"], unique=False
    )
    op.create_table(
        "feature",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("dataset_version_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=300), nullable=False),
        sa.Column("lon", sa.Float(), nullable=False),
        sa.Column("lat", sa.Float(), nullable=False),
        sa.Column(
            "attributes",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["dataset_version_id"], ["dataset_version.id"], ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_feature_dataset_version_id"), "feature", ["dataset_version_id"], unique=False
    )
    op.create_table(
        "assessment_feature",
        sa.Column("assessment_id", sa.Uuid(), nullable=False),
        sa.Column("feature_id", sa.Uuid(), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("reason_code", sa.String(length=64), nullable=False),
        sa.Column("flood_depth_m", sa.Float(), nullable=True),
        sa.Column("vulnerability_value", sa.Float(), nullable=True),
        sa.CheckConstraint(
            "status IN ('potentially_exposed', 'not_exposed_under_scenario', 'unable_to_assess')",
            name="ck_assessment_feature_status",
        ),
        sa.CheckConstraint(
            "vulnerability_value IS NULL OR (vulnerability_value >= 0 AND vulnerability_value <= 1)",
            name="ck_assessment_feature_vulnerability",
        ),
        sa.ForeignKeyConstraint(["assessment_id"], ["assessment.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["feature_id"], ["feature.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("assessment_id", "feature_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    raise RuntimeError("GRP migrations are forward-only; restore a coordinated backup instead")
